#!/bin/bash
# DEPLOYMENT CHECKLIST FOR MAC ADDRESS AUTH + ADD PROGRAMS

echo "╔════════════════════════════════════════════════════════╗"
echo "║  🚀 DEPLOYMENT CHECKLIST - MAC AUTH + ADD PROGRAMS    ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

PROJECT_DIR="/home/boot/Desktop/external_BBP_db"

echo "📋 PRE-DEPLOYMENT STEPS:"
echo ""

echo "1️⃣  ADD YOUR MAC ADDRESSES"
echo "   Location: src/Auth.jsx (line ~18)"
echo "   Add your device's MAC address to AUTHORIZED_MACS:"
echo ""
echo "   const AUTHORIZED_MACS = ["
echo "       '00:1A:2B:3C:4D:5E',  // Demo MAC 1"
echo "       'AA:BB:CC:DD:EE:FF',  // Demo MAC 2"
echo "       'YOUR:MAC:HERE:123',  // Your Mac"
echo "   ];"
echo ""
echo "   To find your MAC:"
echo "   - Windows: ipconfig /all (Physical Address)"
echo "   - Mac: ifconfig | grep HWaddr"
echo "   - Linux: ip link show"
echo ""

echo "2️⃣  REBUILD THE APP"
echo "   cd $PROJECT_DIR"
echo "   npm run build"
echo ""

echo "3️⃣  START THE SERVER"
echo "   cd $PROJECT_DIR/build"
echo "   python3 -m http.server 3000"
echo ""

echo "4️⃣  TEST THE APP"
echo "   Open: http://localhost:3000"
echo "   Login with MAC: AA:BB:CC:DD:EE:FF (demo)"
echo ""

echo "5️⃣  TEST ADD PROGRAM FEATURE"
echo "   Click ➕ Add Target button"
echo "   Enter: https://example.com/bug-bounty"
echo "   Select category: Custom Target"
echo "   Should show 🆕 NEW badge"
echo ""

echo "✅ POST-DEPLOYMENT"
echo "   - Only authorized MAC addresses can login"
echo "   - No email/password signup available"
echo "   - All programs can be searched & filtered"
echo "   - Custom programs get NEW badge (7 days)"
echo "   - Favorites persist in browser storage"
echo "   - Daily scraper runs at 2:00 AM"
echo ""

echo "╔════════════════════════════════════════════════════════╗"
echo "║  FILES MODIFIED                                        ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "✅ src/Auth.jsx"
echo "   - Removed email/password signup"
echo "   - Added MAC address authentication"
echo "   - Added authorized MAC list"
echo ""

echo "✅ src/Auth.css"
echo "   - New MAC input styling"
echo "   - Updated form layout"
echo "   - Default MAC display"
echo ""

echo "✅ src/App.jsx"
echo "   - Header shows MAC address (not email)"
echo "   - Added 'Add Target' button"
echo "   - Added add program modal form"
echo "   - Added addNewProgram() function"
echo ""

echo "✅ src/App.css"
echo "   - Modal styling"
echo "   - Button styling"
echo "   - Form group styling"
echo ""

echo "✅ package.json"
echo "   - Added node-schedule for daily scraper"
echo ""

echo "╔════════════════════════════════════════════════════════╗"
echo "║  FEATURE CHECKLIST                                     ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

echo "✅ Authentication"
echo "   - MAC address login only"
echo "   - No signup or registration"
echo "   - Authorized list management"
echo ""

echo "✅ Add Programs"
echo "   - URL + Category form"
echo "   - Duplicate detection"
echo "   - Automatic NEW badge"
echo "   - Category selection dropdown"
echo ""

echo "✅ Program Management"
echo "   - 1,623+ total programs"
echo "   - 5 platform scrapers"
echo "   - Custom program support"
echo "   - Full search & filter"
echo ""

echo "✅ User Features"
echo "   - 4 emoji favorites (⭐❤️🔥👎)"
echo "   - Dark/light theme"
echo "   - Platform badges"
echo "   - Program icons"
echo "   - Pagination (100 per page)"
echo ""

echo "✅ Data Management"
echo "   - Daily auto-scraping"
echo "   - Backup previous database"
echo "   - NEW badge (7-day duration)"
echo "   - LocalStorage persistence"
echo ""

echo "╔════════════════════════════════════════════════════════╗"
echo "║  DEPLOYMENT COMMANDS                                   ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

echo "# Install dependencies (if needed)"
echo "cd $PROJECT_DIR && npm install"
echo ""

echo "# Rebuild after adding your MAC addresses"
echo "npm run build"
echo ""

echo "# Start web server"
echo "cd build && python3 -m http.server 3000"
echo ""

echo "# Start daily scraper"
echo "cd /home/boot/Desktop/external_BBP_db && npm run scheduler"
echo ""

echo "# Or set up cron job"
echo "crontab -e"
echo "# Add: 0 2 * * * cd /home/boot/Desktop/external_BBP_db && node scraper-master.js >> logs/scraper-\$(date +\\%Y-\\%m-\\%d).log 2>&1"
echo ""

echo "╔════════════════════════════════════════════════════════╗"
echo "║  🎉 READY TO GO!                                       ║"
echo "║                                                        ║"
echo "║  1. Add your MAC addresses to src/Auth.jsx            ║"
echo "║  2. Run: npm run build                                ║"
echo "║  3. Start server on port 3000                         ║"
echo "║  4. Visit: http://localhost:3000                      ║"
echo "║  5. Login with your MAC address                       ║"
echo "║  6. Add new targets with ➕ button                    ║"
echo "║                                                        ║"
echo "╚════════════════════════════════════════════════════════╝"
